version: '3.8'

services:
    laravel-service:
        build:
            context: ./laravel-service
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./laravel-service:/var/www/html
        networks:
            - laravel-network


networks:
    laravel-network:
        driver: bridge
